name: call Building

on:
  push:
    branches: [main]

jobs:
  build-resusable:
    uses: ./.github/workflows/reusable-build.yml
    # fahadjaseem2/github-actions-practice/.github/workflows/reusable-build.yml ( this path use when workflow is another repo)
    with:
      app: "my-web-app"
      environment: "prod"
    secrets:
      docker_token: ${{ secrets.docker_token }}