name: Conditionals WF

on:   
  push:
  pull_request:


jobs:
  Conditionals:
    if: github.event_name == 'push'
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: current branch name
        run: echo "current branch is- ${{ github.ref }}"
      
      - name: runs only main branch
        if: github.ref == 'refs/heads/main'   #branch == main → run, branch != main → skip
        run: echo "this step only run on main branch"

      - name: fail intentionally
        run: exit 1
      
      - name: run only if above step fail
        if: failure()          # success()   → previous steps succeeded. / failure()   → a previous step failed. / always()    → run no matter what. / cancelled()→ run if workflow was cancelled
        run: echo "previous step is fail"




      
        
       