name: Greet User

on:
  push:
    branch: [main]

jobs:
  greet: # error = forget to add jobs name
    runs-on: ubuntu-latest  # error = runs-on wrote _ instead of - 
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 # error = wrote run instead of uses

      - name: greet user
        run: echo "Hello $USER and today date is: $DATE"
