name: job output WF

on:
  workflow_dispatch:

jobs: 
  job-1:
    runs-on: ubuntu-latest

    outputs:
      current-date: ${{ steps.setup-date.outputs.date }}

    steps:
      - name: setting up date for output
        id: setup-date
        run: echo "date=$(date)" >> GITHUB_OUTPUT


  jobs-2:
    needs: job-1
    runs-on: ubuntu-latest

    steps:
      - name: print the current date from job-1
        run: echo "today's date is:${{ needs.job-1.outputs.current-date }}"
     



  