name: manual-workflow 

on:
  workflow_dispatch:
  inputs:
  environment:      # This is the name of the input variable. also use this later on WF (${{ github.event.inputs.environment }})
    discription: 'Target Environment'  #This is the label shown in the GitHub UI.
    recuired: true
    default: 'staging'
    type: choice
    choice:
      - staging
      - production


jobs:
  manual_WF:
    runs_on: ubuntu-latest
  steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: greet
      run: echo "Hello Dosto, this is manual workflow that trigger manually and this workflow is required target environmet"

    - name: Print Environment
      run: echo "deploying to ${{ github.event.inputs.environment }}"   
