name: pull request

on:
  pull_request:
    branches: [main]

jobs:
  task-41:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Print PR branch name
      run: echo "PR check running for branch:${{ github.head_ref }}" # github.head_ref only user for pull req
