name: resusable workflow call

on:
  workflow_call:
    inputs:
      app:
        description: "name of the application"
        required: true
        type: string


      environment: # name of input
        description: "Target Environment"
        required: true
        default: staging
        type: string
        
    secrets:
      docker_token:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Print Building app name for environment
        run: echo " APP Name is :${{ inputs.app }} and Environment is :${{ inputs.environment }}"

      - name: verify docker token
        run: |
          if [ -z "${{ secrets.docker_token }}" ]; then
            echo " Docker Token is set: True"
          else
            echo " Docker Token is set: false"
          fi

