name: reusable build

on:
  workflow_call:

    inputs:
      app_name: 
        description: enter app name
        required: true
        type: string

      environment:
        description: enter the environment
        required: true
        default: staging
        type: string
      
      secrets:
        docker_token:
          required: true
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: print app and environment
        run: echo " Building App is :${{ inputs.app_name }} and environment is :${{ inputs.environment }}"

      - name: set docker token
        run: |
          if [ -z "${{ DOCKER_TOKE }}" ]; then
            echo "Docker token is set"
          else
            echo "Docker token is not set"
          fi      

