name: secret as env variable

on:
  workflow_dispatch:

jobs:
  secret-env-var:
    runs-on: ubuntu-latest 

    steps:
      - name: login docker-hub ussing secret vars.
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"
          if [ $? -eq 0 ]; then
          echo " Docker Logged in succefully "
          else
          echo "Docker Login Failed"
          fi 


