name: smart pipeline

on:
  workflow_dispatch:
  #push:
    #branches:
     # - '**'
      #- '!main'

jobs: 
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: run linter
        run: echo "Running lint check..."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: run linter
        run: echo "Running tests..."

  summary:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        
      - name: current branch name
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "This is Main branch push"
          else
            echo "This is feature branch push"
          fi

      - name: print commit message
        run: echo "commit message is:${{ github.event.head_commit.message }}"
